---
title: "STAT 626 Project"
author: "Group 9"
date: "6/2021 - 8/2021"
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    latex_engine: pdflatex
---

```{r}
library(astsa)
raw <- read.csv("mlb.csv")
era <- ts(rev(raw$ERA), start = raw$Year[length(raw$Year)], end = raw$Year[1])
tsplot(era, main = 'Earned Run Average Time Series', xlab = 'Year', ylab = 'ERA')
```
```{r}
ba <- ts(rev(raw$BA), start = raw$Year[length(raw$Year)], end = raw$Year[1])
tsplot(ba, main = 'Batting Average Time Series', xlab = 'Year', ylab = 'BA')
```
```{r}
hits <- ts(rev(raw$H), start = raw$Year[length(raw$Year)], end = raw$Year[1])
tsplot(hits, main = 'Hits Time Series', xlab = 'Year', ylab = 'Hits')
```
```{r}
hrs <- ts(rev(raw$HR), start = raw$Year[length(raw$Year)], end = raw$Year[1])
tsplot(hrs, main = 'Home Runs Time Series', xlab = 'Year', ylab = 'HRs')
```
```{r}
so <- ts(rev(raw$SO), start = raw$Year[length(raw$Year)], end = raw$Year[1])
tsplot(so, main = 'Strikeouts Time Series', xlab = 'Year', ylab = 'SOs')
```
```{r}
panel.cor <- function(x, y, ...) {
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- round(cor(x, y), 2)
  text(0.5, 0.5, r, cex = 1.75)
}
pairs(cbind(ERA = era, BattingAvg = ba, Hits = hits, Strikeouts = so, HomeRuns = hrs), lower.panel = panel.cor)
```
```{r}
pairs(cbind(ERA = era, BattingAvg = ba, HomeRuns = hrs), lower.panel = panel.cor)
```
a. $ERA_t = \beta_0 + \beta_1 t + w_t$  
b. $ERA_t = \beta_0 + \beta_1 t + \beta_2 HR + w_t$  
c. $ERA_t = \beta_0 + \beta_1 t + \beta_2 HR + \beta_3 HR^2 + w_t$  
d. $ERA_t = \beta_0 + \beta_1 t + \beta_2 HR + \beta_3 HR^2 + \beta_4 BA + w_t$

```{r}
hrs_2 <- hrs^2
trend <- time(era)
fit_a <- lm(era ~ trend)
fit_b <- lm(era ~ trend + hrs)
fit_c <- lm(era ~ trend + hrs + hrs_2)
fit_d <- lm(era ~ trend + hrs + hrs_2 + ba)
```






















